### ISSUE TITLE
Pull requests & Package maintenance

### ISSUE THREAD

**Issue by antonioribeiro** [wiredmax/world-currencies#8]
Do you have plans to keep maintaining this package? I see there are some pull requests and one in particular (kind of old, from @hippietrail) are just typos.

I just merged them all in my fork, but I'll wait for your answer.

**Comment by wiredmax** [comment]
Yes, I was quite busy of the last months and now I'm back, I'll continue maintaining this package. During the spring also we'll do a review if all the data is still actual beyond the PRs that have been opened.
